import { Column } from './../../types/ColumnDictionary'
export const columns: Column[] = [
  {
    key: 'playerImageSrc',
    label: '',
    columnFilter: false,
    isImage: true,
    canSort: false,
    // sticky: 'left',
    display: true,
    type: 'string',
  },
  {
    key: 'rank',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'number',
  },
  {
    key: 'playerName',
    label: 'Name',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'avgAdp',
    label: 'ADP',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'getRoundAndPick',
    label: 'Round & Pick',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'pos',
    label: 'position',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'playerDepthPosition',
    label: 'Depth Position',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'depth',
    label: 'depth',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'byeWeek',
    label: 'Bye Week',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'avgFanPoints',
    label: 'AVG Points',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'avgPassingYds',
    label: 'AVG Passing Yds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'avgPassingTds',
    label: 'AVG Passing Tds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'avgReceivingRec',
    label: 'AVG Receiving Rec',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'avgReceivingYds',
    label: 'AVG Receiving Yds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'avgReceivingTds',
    label: 'AVG Receiving Tds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'avgRushingAtt',
    label: 'AVG Rushing ATT',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'avgRushingYds',
    label: 'AVG Rushing Yds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'avgRushingTds',
    label: 'AVG Rushing Tds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'totalFanPoints',
    label: 'TOTAL Points',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'totalPassingYds',
    label: 'TOTAL Passing Yds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'totalPassingTds',
    label: 'TOTAL Passing Tds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'totalReceivingRec',
    label: 'TOTAL Receiving Rec',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'totalReceivingYds',
    label: 'TOTAL Receiving Yds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'totalReceivingTds',
    label: 'TOTAL Receiving Tds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'totalRushingAtt',
    label: 'TOTAL Rushing ATT',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'totalRushingYds',
    label: 'TOTAL Rushing Yds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'totalRushingTds',
    label: 'TOTAL Rushing Tds',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'strengthOgSchedule',
    label: 'Strength of Schedule',
    columnFilter: false,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'height',
    label: 'height',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'weight',
    label: 'weight',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'experience',
    label: 'experience',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'number',
    label: 'number',
    columnFilter: true,
    type: 'number',
    canSort: true,
    display: true,
  },
  {
    key: 'teamName',
    label: 'Team',
    columnFilter: true,
    canSort: true,
    display: true,
    type: 'string',
  },
  {
    key: 'drafted',
    label: 'Drafted',
    columnFilter: false,
    canSort: false,
    sticky: 'right',
    display: true,
    type: 'string',
  },
]
